/* *************************************************************************
 *   Copyright (C) 12/jan/08 by Salvo "LtWorf" Tomaselli                   *
 *   salvatore.tomaselli@galileo.dmi.unict.it                              *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

package gui;

import users.RemoteUser;

/**
 *
 * @author salvo
 * 
 * This interface must be implemented to listen to the events generated by the UserList
 */
public interface UserListListener {
    
    /**
     * Event generated when a new user is added.
     * Gives the user just
     * @param u
     */
    public void userAdded(RemoteUser u);
    
    /**
     * Generated when the user u is removed from the list because no more online
     * @param u
     */
    public void userRemoved(RemoteUser u);
    
    /**
     * Generated when the user u is changed (usually changed nickname)
     * @param u
     */
    public void userChanged(RemoteUser u);

}
